# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339f2aff44e292cbb0914a49d68cb15b2198c52cf5552f039c308b9e6ab1bdfa44415b3013323c0f8904202eaea1ff4003022dfdd90b0613220761e44d387775

test:
  secret_key_base: 09155a1be639efe88248127d2aa701ea7036874017bda11aa4dd13870271d27d6637ff8f70ac7a179ee0721dfcce95c6dde2af9feb13dc801340c09850ecf383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
